"use client";

import { useState, useTransition } from "react";
import { Button } from "@/components/admin/ui";
import { useToast } from "@/components/admin/Toast";
import { summarizeFeedbackReport } from "./actions";
import type { FeedbackDigest } from "@/lib/ai";

/**
 * On-demand Claude summary of the written feedback for the current period.
 * Generated by button (cost/latency), then shown in the report. Generate it
 * before printing so the PDF carries the summary.
 */
export default function AiSummary({
  from,
  to,
  label,
  aiEnabled,
}: {
  from: string | null;
  to: string | null;
  label: string;
  aiEnabled: boolean;
}) {
  const { error: toastError } = useToast();
  const [digest, setDigest] = useState<FeedbackDigest | null>(null);
  const [pending, start] = useTransition();

  function generate() {
    start(async () => {
      const res = await summarizeFeedbackReport({ from, to, label });
      if (!res.ok) {
        toastError(res.error);
        return;
      }
      setDigest(res.digest);
    });
  }

  return (
    <section className="mt-8 break-inside-avoid">
      <div className="flex items-center justify-between gap-3">
        <h2 className="font-display text-xl font-semibold text-ink">
          Summary of what families said
        </h2>
        <div className="print:hidden">
          <Button
            variant={digest ? "secondary" : "primary"}
            size="sm"
            disabled={pending || !aiEnabled}
            onClick={generate}
          >
            {pending
              ? "Reading responses…"
              : digest
                ? "Regenerate"
                : "Summarize with Claude"}
          </Button>
        </div>
      </div>

      {!aiEnabled && (
        <p className="mt-2 text-sm text-ink-faint">
          AI summary is not configured (set ANTHROPIC_API_KEY).
        </p>
      )}

      {!digest && aiEnabled && (
        <p className="mt-2 text-sm text-ink-soft print:hidden">
          Click “Summarize with Claude” to pull the key themes from the written
          comments in this period. It reads only the real responses (it never
          invents anything). Generate it before printing to include it in the PDF.
        </p>
      )}

      {digest && (
        <div className="mt-3 rounded-xl border border-line bg-white p-5 shadow-sm">
          <p className="text-[15px] leading-relaxed text-ink">{digest.overview}</p>

          {digest.praises.length > 0 && (
            <div className="mt-4">
              <p className="text-xs font-semibold uppercase tracking-wide text-sage">
                What families praise
              </p>
              <ul className="mt-1.5 list-disc space-y-1 pl-5 text-sm text-ink">
                {digest.praises.map((p, i) => (
                  <li key={i}>{p}</li>
                ))}
              </ul>
            </div>
          )}

          {digest.improvements.length > 0 && (
            <div className="mt-4">
              <p className="text-xs font-semibold uppercase tracking-wide text-gold">
                What to improve
              </p>
              <ul className="mt-1.5 list-disc space-y-1 pl-5 text-sm text-ink">
                {digest.improvements.map((p, i) => (
                  <li key={i}>{p}</li>
                ))}
              </ul>
            </div>
          )}

          {digest.quotes.length > 0 && (
            <div className="mt-4">
              <p className="text-xs font-semibold uppercase tracking-wide text-ink-faint">
                In their words
              </p>
              <div className="mt-1.5 space-y-2">
                {digest.quotes.map((q, i) => (
                  <p
                    key={i}
                    className="border-l-2 border-clay pl-3 text-sm italic text-ink-soft"
                  >
                    “{q}”
                  </p>
                ))}
              </div>
            </div>
          )}

          <p className="mt-4 text-xs text-ink-faint">
            Written by Claude from the {label.toLowerCase()} responses. Review
            before sharing.
          </p>
        </div>
      )}
    </section>
  );
}
